name: Deploy Smart Trash App to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: 16.78.2.119
          username: ubuntu
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Masuk ke direktori aplikasi (buat jika belum ada)
            mkdir -p ~/smart-trash-app && cd ~/smart-trash-app
            
            # Ambil update kode terbaru
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/Afr17/smart-trash-app.git .
            fi
            
            # Membuat file .env otomatis dari GitHub Secrets
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
            echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
            echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env
            
            # Build Docker Image dan Jalankan Container
            sudo docker build -t smart-trash-app .
            sudo docker rm -f smart-trash-container || true
            sudo docker run -d -p 80:3000 --env-file .env --name smart-trash-container smart-trash-app